---
language: python
sudo: false
python:
  - "3.6"

install:
  - pip install -U tox-travis

script:
  - if [[ "${TRAVIS_TAG}" == "" ]]; then
      tox -e py36 && docker build -t datawire/ambassador-auth-httpbasic .
    fi

after_script: []

deploy:
  - provider: script
    skip_cleanup: true
    script: ./publish.sh
    on:
      tags: false
      branch: master
#  - provider: script
#    skip_cleanup: true
#    script: ./release.sh
#    on:
#      tags: true
#      branch: master